name:                apple-localauthenticationembeddedui-localauthentication-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the LocalAuthenticationEmbeddedUI extensions on LocalAuthentication framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen
- apple-localauthentication-gen
- apple-localauthenticationembeddedui-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.LocalAuthenticationEmbeddedUI.LARight
