name:                apple-accessorysetupkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AccessorySetupKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AccessorySetupKit.ASAccessory
  - ObjC.AccessorySetupKit.ASAccessoryEvent
  - ObjC.AccessorySetupKit.ASAccessorySession
  - ObjC.AccessorySetupKit.ASAccessorySettings
  - ObjC.AccessorySetupKit.ASDiscoveredAccessory
  - ObjC.AccessorySetupKit.ASDiscoveredDisplayItem
  - ObjC.AccessorySetupKit.ASDiscoveryDescriptor
  - ObjC.AccessorySetupKit.ASMigrationDisplayItem
  - ObjC.AccessorySetupKit.ASPickerDisplayItem
  - ObjC.AccessorySetupKit.ASPickerDisplaySettings
  - ObjC.AccessorySetupKit.ASPropertyCompareString
  - ObjC.AccessorySetupKit.Enums
  - ObjC.AccessorySetupKit.Internal.Classes
  - ObjC.AccessorySetupKit.Internal.Enums
