name:                apple-intentsui-intents-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the IntentsUI extensions on Intents framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-appkit-gen
- apple-intents-gen
- apple-intentsui-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.IntentsUI.INImage
