name:                apple-ituneslibrary-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ITunesLibrary framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ITunesLibrary.Enums
  - ObjC.ITunesLibrary.ITLibAlbum
  - ObjC.ITunesLibrary.ITLibArtist
  - ObjC.ITunesLibrary.ITLibArtwork
  - ObjC.ITunesLibrary.ITLibMediaEntity
  - ObjC.ITunesLibrary.ITLibMediaItem
  - ObjC.ITunesLibrary.ITLibMediaItemVideoInfo
  - ObjC.ITunesLibrary.ITLibPlaylist
  - ObjC.ITunesLibrary.ITLibrary
  - ObjC.ITunesLibrary.Internal.Classes
  - ObjC.ITunesLibrary.Internal.Enums
