name:                apple-driverkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the DriverKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.DriverKit
  - ObjC.DriverKit.Enums
  - ObjC.DriverKit.Internal.Enums
  - ObjC.DriverKit.Internal.Structs
  - ObjC.DriverKit.Structs
