name:                apple-coreaudiokit-audiotoolbox-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CoreAudioKit extensions on AudioToolbox framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-audiotoolbox-gen
- apple-coreaudiokit-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CoreAudioKit.AUAudioUnit
