name:                apple-threadnetwork-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ThreadNetwork framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ThreadNetwork.Internal.Classes
  - ObjC.ThreadNetwork.THClient
  - ObjC.ThreadNetwork.THCredentials
