name:                apple-symbols-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Symbols framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Symbols.Internal.Classes
  - ObjC.Symbols.NSSymbolAppearEffect
  - ObjC.Symbols.NSSymbolAutomaticContentTransition
  - ObjC.Symbols.NSSymbolBounceEffect
  - ObjC.Symbols.NSSymbolBreatheEffect
  - ObjC.Symbols.NSSymbolContentTransition
  - ObjC.Symbols.NSSymbolDisappearEffect
  - ObjC.Symbols.NSSymbolDrawOffEffect
  - ObjC.Symbols.NSSymbolDrawOnEffect
  - ObjC.Symbols.NSSymbolEffect
  - ObjC.Symbols.NSSymbolEffectOptions
  - ObjC.Symbols.NSSymbolEffectOptionsRepeatBehavior
  - ObjC.Symbols.NSSymbolMagicReplaceContentTransition
  - ObjC.Symbols.NSSymbolPulseEffect
  - ObjC.Symbols.NSSymbolReplaceContentTransition
  - ObjC.Symbols.NSSymbolRotateEffect
  - ObjC.Symbols.NSSymbolScaleEffect
  - ObjC.Symbols.NSSymbolVariableColorEffect
  - ObjC.Symbols.NSSymbolWiggleEffect
