name:                haskell-obj-c-bundler
version:             0.1.0.0
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

synopsis:            macOS .app bundle creator for GHC-dynamic Haskell executables
category:            Distribution

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- filepath
- process
- text
- xml-conduit
- xml-types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Bundler.Types
  - ObjC.Bundler.Dylib
  - ObjC.Bundler.Plist
  - ObjC.Bundler.Bundle

executables:
  objc-bundler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-obj-c-bundler
    - optparse-applicative
