name:                apple-classkit-foundation-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ClassKit extensions on Foundation framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-classkit-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ClassKit.NSUserActivity
