name:                apple-devicecheck-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the DeviceCheck framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.DeviceCheck.DCAppAttestService
  - ObjC.DeviceCheck.DCDevice
  - ObjC.DeviceCheck.Enums
  - ObjC.DeviceCheck.Internal.Classes
  - ObjC.DeviceCheck.Internal.Enums
