name:                apple-cinematic-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Cinematic framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-avfoundation-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Cinematic.CNAssetInfo
  - ObjC.Cinematic.CNAssetSpatialAudioInfo
  - ObjC.Cinematic.CNBoundsPrediction
  - ObjC.Cinematic.CNCompositionInfo
  - ObjC.Cinematic.CNCustomDetectionTrack
  - ObjC.Cinematic.CNDecision
  - ObjC.Cinematic.CNDetection
  - ObjC.Cinematic.CNDetectionTrack
  - ObjC.Cinematic.CNFixedDetectionTrack
  - ObjC.Cinematic.CNObjectTracker
  - ObjC.Cinematic.CNRenderingSession
  - ObjC.Cinematic.CNRenderingSessionAttributes
  - ObjC.Cinematic.CNRenderingSessionFrameAttributes
  - ObjC.Cinematic.CNScript
  - ObjC.Cinematic.CNScriptChanges
  - ObjC.Cinematic.CNScriptFrame
  - ObjC.Cinematic.Enums
  - ObjC.Cinematic.Internal.Classes
  - ObjC.Cinematic.Internal.Enums
