name:                apple-sharedwithyou-appkit-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the SharedWithYou extensions on AppKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-appkit-gen
- apple-sharedwithyou-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.SharedWithYou.NSPasteboardItem
