name:                apple-devicediscoveryextension-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the DeviceDiscoveryExtension framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen
- apple-uniformtypeidentifiers-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.DeviceDiscoveryExtension.DDDevice
  - ObjC.DeviceDiscoveryExtension.DDDeviceEvent
  - ObjC.DeviceDiscoveryExtension.DDDiscoverySession
  - ObjC.DeviceDiscoveryExtension.Enums
  - ObjC.DeviceDiscoveryExtension.Internal.Classes
  - ObjC.DeviceDiscoveryExtension.Internal.Enums
