name:                apple-mediaextension-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the MediaExtension framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.MediaExtension.Enums
  - ObjC.MediaExtension.Internal.Classes
  - ObjC.MediaExtension.Internal.Enums
  - ObjC.MediaExtension.MEByteSource
  - ObjC.MediaExtension.MEDecodeFrameOptions
  - ObjC.MediaExtension.MEEstimatedSampleLocation
  - ObjC.MediaExtension.MEFileInfo
  - ObjC.MediaExtension.MEFormatReaderInstantiationOptions
  - ObjC.MediaExtension.MEHEVCDependencyInfo
  - ObjC.MediaExtension.MERAWProcessingBooleanParameter
  - ObjC.MediaExtension.MERAWProcessingFloatParameter
  - ObjC.MediaExtension.MERAWProcessingIntegerParameter
  - ObjC.MediaExtension.MERAWProcessingListElementParameter
  - ObjC.MediaExtension.MERAWProcessingListParameter
  - ObjC.MediaExtension.MERAWProcessingParameter
  - ObjC.MediaExtension.MERAWProcessingSubGroupParameter
  - ObjC.MediaExtension.MERAWProcessorPixelBufferManager
  - ObjC.MediaExtension.MESampleCursorChunk
  - ObjC.MediaExtension.MESampleLocation
  - ObjC.MediaExtension.METrackInfo
  - ObjC.MediaExtension.MEVideoDecoderPixelBufferManager
